server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index en.html;

    location = /       { return 301 /en/; }
    location = /en     { return 301 /en/; }
    location = /vn     { return 301 /vn/; }
    location = /th     { return 301 /th/; }
    location = /id     { return 301 /id/; }

    location /en/ { try_files /en.html =404; }
    location /vn/ { try_files /vn.html =404; }
    location /th/ { try_files /th.html =404; }
    location /id/ { try_files /id.html =404; }

    gzip on;
    gzip_types text/html;
    gzip_min_length 1024;
}
